services:
  backend:
    build:
      context: ./
    image: taxchatbotllm
    ports:
      - "8000:8000"
    command: sh -c "chmod +x migrate.sh && sh ./migrate.sh && sh ./entrypoint.sh"
    volumes:
      - ./:/app
    env_file:
      .env
    environment:
      - DB_HOST=db
    depends_on:
      - db
  
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5423:5432
    expose:
      - "5423"
    env_file:
      .env

volumes:
    postgres_data:
