# Generated by Django 4.2.11 on 2024-04-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_w2form_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='w2form',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
