# Generated by Django 4.2.11 on 2024-04-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_w2form_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='w2form',
            name='messages',
            field=models.JSONField(default='{}'),
            preserve_default=False,
        ),
    ]
