# Generated by Django 4.2.11 on 2024-04-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_w2form_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='w2form',
            name='messages',
        ),
    ]
