# Generated by Django 4.2.11 on 2024-04-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_w2form_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='w2form',
            name='messages',
            field=models.JSONField(default='[]'),
            preserve_default=False,
        ),
    ]
