# Generated by Django 4.2.11 on 2024-04-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_w2form_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='w2form',
            name='encrypted_ssn',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
