# Generated by Django 4.2.11 on 2024-04-30 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_w2form_encrypted_ssn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='w2form',
            old_name='encrypted_ssn',
            new_name='employee_ssn',
        ),
    ]
