# Generated by Django 4.2.11 on 2024-04-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_encrypted_ssn_w2form_employee_ssn'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='secret_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
