name: Create Docker Image, Push to Docker Hub and Deploy to AWS EBS

on:
  push:
    branches:
      - master
env:
    DOCKER_IMAGE_NAME: wolvezine24/taxchatbotllm
    DOCKER_IMAGE_TAG: production
    AWS_EB_APPLICATION_NAME: taxchatbotlm
    AWS_EB_ENVIRONMENT_NAME: Taxchatbotlm-env

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Explain why this job ran
      run: echo "The event that triggered is ${{ github.event_name }} event"

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} .

    - name: Push Docker image to Docker Hub
      run: docker push ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
    
    - name: Generate deployment package
      run: zip -r deploy.zip Dockerrun.aws.json -x '*.git*'

    - name: Deploy to AWS Elastic Beanstalk (New Version)
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ env.AWS_EB_APPLICATION_NAME }}
        environment_name: ${{ env.AWS_EB_ENVIRONMENT_NAME }}
        version_label: production-${{ github.sha }}
        region: 'ap-northeast-1'
        deployment_package: deploy.zip
      if: github.ref == 'refs/heads/master' && github.event_name != 'workflow_run'
    
    - name: Deploy to AWS Elastic Beanstalk (Re-Deploy same version)
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ env.AWS_EB_APPLICATION_NAME }}
        environment_name: ${{ env.AWS_EB_ENVIRONMENT_NAME }}
        version_label: production-${{ github.sha }}
        region: 'ap-northeast-1'
        use_existing_version_if_available: true
      if: github.ref == 'refs/heads/master' && github.event_name == 'workflow_run'